const icons={message:'<path d="M21 11.5a8.4 8.4 0 0 1-.9 3.8 8.5 8.5 0 0 1-7.6 4.7 8.4 8.4 0 0 1-3.8-.9L3 21l1.9-5.7a8.4 8.4 0 0 1-.9-3.8 8.5 8.5 0 0 1 4.7-7.6 8.4 8.4 0 0 1 3.8-.9h.5a8.5 8.5 0 0 1 8 8z"/><path d="M8 10h8M8 14h5"/>',mic:'<rect x="9" y="2" width="6" height="12" rx="3"/><path d="M5 10v2a7 7 0 0 0 14 0v-2M12 19v3M8 22h8"/>',video:'<rect x="2" y="5" width="14" height="14" rx="3"/><path d="m16 10 6-4v12l-6-4z"/>',shield:'<path d="M12 3 3 7v5c0 5 9 10 9 10s9-5 9-10V7zM8 12l3 3 5-6"/>'};
const $=id=>document.getElementById(id), video=$('video');
icons.gov='<path d="m3 9 9-6 9 6H3zM5 10v9M10 10v9M14 10v9M19 10v9M2 21h20"/>';
const groups=[{id:'whatsapp',title:'WhatsApp',num:'01',text:'Para conversar e compartilhar o dia a dia.',lessons:[1,2]},{id:'gov',title:'Site Gov.br',num:'02',text:'Para conhecer os serviços públicos digitais.',lessons:[3,4]},{id:'seguranca',title:'Segurança contra golpes',num:'03',text:'Para usar a tecnologia com mais cuidado.',lessons:[5,6]}];
$('lessonCards').innerHTML=groups.map(g=>`<section class="course-group" id="${g.id}"><div class="group-heading"><span>${g.num}</span><div><h3>${g.title}</h3><p>${g.text}</p></div><small>2 vídeos</small></div><div class="cards">${g.lessons.map((id,i)=>{const a=window.AULAS[id];return `<button class="card" data-lesson="${a.id}" aria-label="Abrir ${g.title}, vídeo ${i+1}: ${a.title}"><div class="card-art"><img class="lesson-cover" src="${a.cover}" alt="Capa: ${a.title}" loading="lazy"><span class="tiny-play">▶</span></div><div class="card-content"><h3>${a.title}</h3><p>${a.subtitle}</p><span class="card-action">${a.video ? 'Assistir à aula' : 'Conhecer a aula'} <span aria-hidden="true">↗</span></span></div></button>`;}).join('')}</div></section>`).join('');
const names=['Arthur','Carlos','Everson','Lucas Gabriel','Lucas Emanuel','Levi','Nicolas','Pedro Melo','Matheus Henrique','Vitor Guilherme'];
const teamPhotos={'Arthur':'capas/artur.png','Pedro Melo':'capas/melo.png'};
$('teamGrid').innerHTML=names.map(n=>`<div class="person"><span class="avatar" aria-hidden="true">${teamPhotos[n]?`<img src="${teamPhotos[n]}" alt="">`:n.split(' ').map(w=>w[0]).join('')}</span><span>${n}</span></div>`).join('');
const controls=['play','centerPlay','seek','mute','volume','full'];
function loadLesson(id,scroll=true){const a=window.AULAS[id];video.pause();video.removeAttribute('src');video.load();$('poster').style.display='flex';$('coverImage').src=a.cover;$('coverImage').alt='Capa: '+a.title;video.poster=a.cover;$('lessonTag').textContent=id?'AULA SELECIONADA':'COMECE POR AQUI';$('counter').textContent=`0${id+1} / 07`;$('posterCaption').textContent=a.category;$('posterTitle').innerHTML=a.poster;$('lessonNum').textContent=`0${id}`;$('currentTitle').textContent=a.title;$('currentDesc').textContent=a.subtitle;$('time').textContent='0:00 / 0:00';$('seek').value=0;$('videoState').textContent=a.video?'Carregando vídeo…':'Vídeo disponível em breve';controls.forEach(i=>$(i).disabled=true);if(a.video)video.src=a.video;document.querySelectorAll('.card').forEach(c=>{const selected=Number(c.dataset.lesson)===id;c.classList.toggle('selected',selected);c.setAttribute('aria-pressed',String(selected));});if(scroll)$('sala').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'center'});}
document.querySelectorAll('.card').forEach(c=>c.addEventListener('click',()=>loadLesson(Number(c.dataset.lesson))));
document.querySelector('.primary').addEventListener('click',()=>loadLesson(0,false));
video.addEventListener('loadedmetadata',()=>{controls.forEach(i=>$(i).disabled=false);$('videoState').textContent='Toque para assistir';updateTime();});
video.addEventListener('error',()=>{$('poster').style.display='flex';$('videoState').textContent='Não foi possível carregar o vídeo. Tente novamente mais tarde.';controls.forEach(i=>$(i).disabled=true);});
function toggle(){if(video.paused)video.play().catch(()=>{$('videoState').textContent='Toque novamente para reproduzir.';});else video.pause();}
$('play').onclick=toggle;$('centerPlay').onclick=toggle;video.onclick=toggle;
video.addEventListener('play',()=>{$('poster').style.display='none';$('play').textContent='Ⅱ';$('play').setAttribute('aria-label','Pausar');});video.addEventListener('pause',()=>{$('play').textContent='▶';$('play').setAttribute('aria-label','Reproduzir');});
function fmt(t){if(!Number.isFinite(t))return '0:00';return `${Math.floor(t/60)}:${String(Math.floor(t%60)).padStart(2,'0')}`;}
function updateTime(){$('time').textContent=`${fmt(video.currentTime)} / ${fmt(video.duration)}`;$('seek').value=video.duration?video.currentTime/video.duration*100:0;}
video.addEventListener('timeupdate',updateTime);$('seek').oninput=e=>{if(Number.isFinite(video.duration))video.currentTime=e.target.value/100*video.duration;};$('volume').oninput=e=>{video.volume=Number(e.target.value);video.muted=video.volume===0;syncMute();};function syncMute(){$('mute').textContent=video.muted?'×':'♪';$('mute').setAttribute('aria-label',video.muted?'Ativar som':'Silenciar');}$('mute').onclick=()=>{video.muted=!video.muted;syncMute();};$('full').onclick=()=>{if(video.requestFullscreen){video.controls=true;video.requestFullscreen().catch(()=>{video.controls=false;});}else if(video.webkitEnterFullscreen)video.webkitEnterFullscreen();};document.addEventListener('fullscreenchange',()=>{if(!document.fullscreenElement)video.controls=false;});$('fontButton').onclick=()=>{const on=document.documentElement.classList.toggle('large-text');document.documentElement.style.fontSize=on?'20px':'16px';$('fontButton').setAttribute('aria-pressed',String(on));};
loadLesson(0,false);
